### ISSUE TITLE
Tchibo_cz změnilo urls produktů

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1005]
a (zřejmě) v návaznosti na to nám nefunguje extenze a nepárují se data v Hlídači. Příklad:
Já v aktuálních datech (z dneška 15.2.) mám:
itemId 400152335
itemName Cafissimo easy - Cafissimo easy, RED - Cafissimo easy, RED
itemUrl https://www.tchibo.cz/cafissimo-easy-red-p400152335.html
Když jdu na tu url, změní se adresa na
https://www.tchibo.cz/products/402076584/cafissimo-easy-powder-rose
tj jiný formát url a jiná barevná varianta produktu
a Hlídač ani extenze produkt nenajde
Pokud dám na webu Tchiba vyhledat ten itemId z našich dat (400152335):
najde to produkt ve variantě Red (což odpovídá názvu v našich datech)
ale s jiným url https://www.tchibo.cz/products/402076584/cafissimo-easy-powder-rose?dim1=Red2
a Hlídač zase produkt v datech nenajde

**Comment by salax** [comment]
fixed in new version
