### ISSUE TITLE
DM_cz extenze - špatně bere originalPrice (v datech ze scrapu mám originalPrice správně)

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1031]
př:
https://www.dm.cz/ebelin-vlhcene-ubrousky-p4010355910264.html
https://www.dm.cz/nuk-myci-koncentrat-500-ml-pro-pripravu-1000-ml-prostredku-p4008600385455.html (edited)

**Comment by salax** [comment]
fixed
