### ISSUE TITLE
Megapixel - vyměnit logo v dashboardu za barevné

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1035]
https://github.com/topmonks/hlidac-shopu/blob/trunk/www.hlidacshopu.cz/src/icons/megapixel_logo.svg
![Logo_Megapxel_cz (1)](https://user-images.githubusercontent.com/82106162/222402315-a0bbb52a-859b-4582-9ae6-5cd932496672.svg)

**Comment by salax** [comment]
done
