### ISSUE TITLE
Megapixel_cz extenze - slug jako path z url není unikátní

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1154]
Potřebuju slug rozšířit na path+query, aby slug respektoval varianty produktu. Takže slug by byl
(PARSE_URL("itemUrl") :path)||'_'||(PARSE_URL("itemUrl") :query)
Příklad:
https://www.megapixel.cz/canon-eos-m200-15-45-mm?v=7267 (černý)
=> v tuto chvíli slug: canon-eos-m200-15-45-mm
=> nově: canon-eos-m200-15-45-mm_v=7267
https://www.megapixel.cz/canon-eos-m200-15-45-mm?v=7269 (bílý)
=> v tuto chvíli slug: canon-eos-m200-15-45-mm
=> nově: canon-eos-m200-15-45-mm_v=7269

**Comment by MartinaGelnerova** [comment]
Megapixel upravil feed tak, aby souhlasily itemUrl ve feedu a na webu.
Nově jsou ty dva problémové produkty ve feedu takto:
itemId 66281: https://www.megapixel.cz/canon-eos-m200-15-45-mm
itemId 66286: https://www.megapixel.cz/canon-eos-m200-15-45-mm?barva=bila
Koukám, že překlikávání variant na webu tomu odpovídá.
Takže slug upravíme tak, aby respektoval i query, pokud v url je?
Pro ty dva produkty to vrací
canon-eos-m200-15-45-mm
canon-eos-m200-15-45-mm_barva=bila

**Comment by MartinaGelnerova** [comment]
@salax :arrow_up:

**Comment by salax** [comment]
změněno (neni potřeba nová extenze)

**Comment by MartinaGelnerova** [comment]
checked, ok
