### ISSUE TITLE
Hromadný f*up actorů

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1157]
Některé actory nahoře u runu mají hlášku There was an uncaught exception during the run of the actor and it was not handled.
- [x] Electroworld https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/2tM4nk2Cp4QoUV7Cm/runs/726aaq6KFoz9fMhwb#log
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@crawlee/http' imported from /home/myuser/main.js
- [x] KnihyDobrovsky
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/NUjB7brjS5iLQ0lFd/runs/seVOUiUmEJpqUUVog#log
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@crawlee/http' imported from /usr/src/app/main.js
- [ ] TSBohemia
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/H36Bqott5Cl1tr7dm/runs/pomla0LhkIYxjnEky#log
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/session_pool/session.js' is not defined by "exports" in /home/myuser/node_modules/apify/package.json imported from /home/myuser/main.js
- [x] Lekarna_cz
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/vt1cmT6tkCmslT9wF/runs/g7dPpyPq4tgAULfXC#log
TypeError: Cannot destructure property 'log' of 'Apify.utils' as it is undefined.

- [x] Hornnach_cz/sk
Jiná chybová hláška nahoře u runu Actor finished with an error (exit code 91)
CZ: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/ODO9pCdwnhV4SnB5U/runs/rK29igwUNPAlOxbdP#log
SK: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/IlDkOaPtnrhNvQpgb/runs/3B2RggEml7Hiurorn#log

Další actory jsou succeeded ale vrátí 0 items:
- [x] Rohlík_cz
Najde produkty v kategoriích, ale vrátí 0 items a tváří se jako succeeded
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/PEVAiXtTjfBAwaOa6/runs/lgyofl38FFz6x6xzm#log
- [x] Benu_cz
V kategoriích nenachází produkty...
https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/wMM5kHLiapiXApP79/runs/qQ3fQ7bP4bNu8beHf#log

**Comment by salax** [comment]
For now incompatible actors are reverted to older version.

**Comment by MartinaGelnerova** [comment]
knihyDobrovsky jsou zaškrtnutý jako funkční, ale last run je fail, 235k items ale Failed Actor finished with an error (exit code 91) =>znovu jsem odškrtla
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/NUjB7brjS5iLQ0lFd/runs/DhVFjYAhOZtx2sMKK#log
