### ISSUE TITLE
Rohlik_cz - dlouho běží, ale vrátí jen jednotky items (místo 20+k items)

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1201]
failed with OOM
problém od 25.4.
last run: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/PEVAiXtTjfBAwaOa6/runs/AfFA9BOQReazQxgiI#log

**Comment by salax** [comment]
fixed
