### ISSUE TITLE
Knihydobrovský - položky "zdarma" extenze i scraper vrací currentPrice=null

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1203]
Knihydobrovský - hodně položek nabízí "zdarma", což jak extenze tak scraper neumí vyhodnotit a vrací null.
Jedná se o 107tis items, které mi neprojdou přes validation schema.
Šlo by upravit scraper a extenzi, aby "zdarma" brali jako 0?
příklad: https://www.knihydobrovsky.cz/e-kniha/ti-co-vidi-532520801

**Comment by salax** [comment]
Mělo by bejt hotový (kromě extenze, která ještě neni vydaná).
