### ISSUE TITLE
iTesco_cz/sk succeeded with 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1245]
problém je to třetí den (od 15.5.)
last run CZ: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/L48jIjbkN9oQlUQY9/runs/jLpgRtLzu1aQlumzM#log
last run SK: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/wASaIqALSVN65yR2o/runs/UWzf2RoMCe1Ggf2Pc#log

**Comment by salax** [comment]
fixed
