### ISSUE TITLE
Lidl_cz - vrací málo items (800+ místo 8000+)

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1246]
problém od 12.5.
Přijde mi, že třeba špatně crowlujeme - první produkty v kategorii vždycky mám, ale když si kategorii seřadím od nejdražších, žádný z těch produktů jsem v datech neměla.
Příklad produktů které nemám v datech:
https://www.lidl.cz/p/zundapp-mestske-elektrokolo-z905/p100354992
https://www.lidl.cz/p/hn8-schlafsysteme-7zonova-tastickova-matrace-xxl-gelstar-t-1000/p100225852
https://www.lidl.cz/p/ecovacs-roboticky-vysavac-deebot-t9/p100357359
https://www.lidl.cz/p/chicco-kocarek-trio-sprint-black-s-kit-car-2017/p100217679
Last run: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/RS4d571fc6LANBU3X/runs/6TlfkOl8nzGLjAifd#storage

**Comment by salax** [comment]
fixed
