### ISSUE TITLE
Eva_cz - success with 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1309]
problém od 10.6.
RequestError: Stream closed with error code NGHTTP2_REFUSED_STREAM
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/Mjxf4bmAzqeo4cfCd/runs/fOZhQ60Kv1Xf8bDaa#log

**Comment by salax** [comment]
dneska už to vypadá ok, tak uvidíme...
