### ISSUE TITLE
AAAauto.cz - succeeded with 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1347]
TypeError: Cannot read properties of null (reading 'getAttribute')
problém od 21.6.
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/HYm1EMUyU0Z4L4wuo/runs/aECsZiAy9goIODFvS#log

**Comment by salax** [comment]
fixed
