### ISSUE TITLE
Alza.cz - nezobrazuje se extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1417]
na webu Hlídače se produkt napáruje a historii zobrazí, na webu Alzy se extenze ale nezobrazí.
např: https://www.alza.cz/bosch-smv6zdx49e-d6124827.htm

**Comment by Losinsky** [comment]
Ani mě to v Alze od včerejška nefunguje.
FF 115.0.2

**Comment by fanick1** [comment]
```
content.js:24004 TypeError: Cannot read properties of null (reading 'dataset')
    at getDetailItemInfo (content.js:22741:56)
    at Alza.scrape (content.js:22746:14)
    at Alza.scheduleRendering (content.js:22500:31)
    at handleDetail (content.js:23948:17)
    at main (content.js:24002:11)
    at content.js:24004:3
    at content.js:24005:3
```
Na strance se nenajde obrazek se zbozim: 
`    const imageUrl = document.querySelector("#imgMain").dataset["src"];`

Na  prasaka mi zabralo nastavit nejakou dummy fallback value (grafik s cenou mi potom naskoci).

**Comment by Losinsky** [comment]
Omlouvám se ale tomuto dialektu nerozumím. Připadá mi to, jako by se tam chaoticky prolínaly 3 různé jazyky.
Bude to rozšíření opraveno/upraveno tak, aby se opět graf zobrazoval? Kdy?

**Comment by fanick1** [comment]
Poprosím o upvote na opravičku #1427

**Comment by MartinaGelnerova** [comment]
checked, ok, closing the issue
