### ISSUE TITLE
Nefunguje upload do Kebooly pro Mountfield

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1458]
Scrape proběhne, v logu se napíše, že upload do Kebooly proběhl úspěšně, ale data v Keboole nemám a v logu uploader jsou errory:
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/xLX9YWZgmvyif9GWp/runs/lKulYDlJaphOcVlIR#log
Poslední data se přenesla 27.7. (nevím, jestli se tam pak něco měnilo...)

**Comment by JJetmar** [comment]
Podle toho co jsem procházel tady nastalo více věcí najednou:
1. Nastala chyba při posílání dat do Kebooly, která skončila s HTTP statusem 400 (nevím jaká viz dále):
  - Tím pádem nastala větev kódu, která bere atribut `message` z Response pro `KEBOOLA_URI`.
    - Jenže se zdá, že takový atribut neexistuje viz výchozí chybový Response na `KEBOOLA_URI`:
      
    ```json
    {
      "error": "Parameter \"tableId\" is required",
      "code": 422,
      "exceptionId": "exception-ba7526907421e5a95c10e2491dc747f2",
      "status": "error",
      "context": []
    }
    ```
    - Takže se [vyhodila vyjímka bez chybové zprávy](https://github.com/topmonks/hlidac-shopu/blob/c76840e159d9833a7290c9026fbb25fc53b2fe25/actors/uploader/src/uploader.js#L45)
    - Díky čemuž jsme úplně ztratili původní chybu a není součástí logu.
2. Dále součásti obsluhy vyjímky je zápis CSV souboru do KV-storu
  - Jen že v rámci [1d4f7796a1fe02a14bb50af52bf2f353935b2303](https://github.com/topmonks/hlidac-shopu/commit/1d4f7796a1fe02a14bb50af52bf2f353935b2303#diff-c80312310c1ac888955a93ae3f0f43f25cdf4de7c62a7e3ad4d224edfb7d7b33R341), došlo ke změně z `Buffer` na `Blob`. Jaký byl důvod @salax ?
  - KV-store zdá se nepodporuje `Blob`, a tím pádem nastává chyba, kterou už vidíme v logu. Jedná se ale o neobslouženou vyjímku, tím pádem se [přeskočí závěrečná podmínka](https://github.com/topmonks/hlidac-shopu/blob/c76840e159d9833a7290c9026fbb25fc53b2fe25/actors/uploader/src/uploader.js#L64) a Run Uploaderu neskončí jako `Failed` nýmbrž jako `Suceeded`, a proto v Logu Actora vidíme:
  
    > že upload do Kebooly proběhl úspěšně

Problém se v rámci Uploader Actora neobjevuje pravidelně, takže se jedná spíše o nahodilí problém, tím že jsme ale přišli o původní chybovou zprávu, nejsme schopni zjistit co přesně se stalo.

#### Co můžeme udělat:
- přesunout inicializaci `Blob` až do momentu, kdy se odesílají data to Kebooly (pokud je vůbec potřeba),
- vylepšit logování chyb z Kebooly - ideálně celé tělo Response, a nemít to závislé na jednom parametru.

**Comment by salax** [comment]
2. Ke změně došlo z důvodu switche z `fetch-h2` knihovny (potažmo `form-data` knihovny) na jejich nativní verze obsažený v Node 18, která právě nepodporuje Buffer, ale Blob (pokud si správně pamatuju).

Je divný, ale že se ta chyba projevuje jenom nahodile... Každopádně bych začal, vylepšenim toho logování/handlování výjimek a pak snad uvidíme víc.

**Comment by JJetmar** [comment]
Díky za info, připravím PR.

Nenastává to nahodile, je to podmíněno tou chybou při uploadu, jak jsem psal výše - bohužel tu chybu nemáme v logu.

**Comment by JJetmar** [comment]
PR #1465
