### ISSUE TITLE
Kosik - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1461]
log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/wIx8FhzstQOLjBBKr/runs/WJSyNT2PlV2lgPaK4#log

když kouknu do detailu nějakého produktu, který se to snaží stáhnout, je tam status 400
```
"status": 400,
"type": "common/invalid-parameter",
"title": "Invalid parameter",
"detail": "Using of limit over 30 products is denied -> use cursor to load more products.",
"instance": "7d84e21d1f6b/1691669927/3a0c6c24-fa05-47bc-8414-a4b463586d27",
"context": {
"invalidParameter": "limit",
"traceId": "ada6aca4edc882a6eee351b8514ec1b4",
"transactionId": "c8b706b6f6bddd1e",
"spanId": "0000000000000000"
}
```
např: https://www.kosik.cz/api/front/page/products?slug=uzeniny-a-lahudky%2Fvyvary%2Fhovezi&limit=60

**Comment by salax** [comment]
fixed
