### ISSUE TITLE
Waterfox compatibility

### ISSUE THREAD

**Issue by gitthangbaby** [theodik/hlidac-shopu#1471]
The most recent Waterfox won't work with the plugin.

Published August 1, 2023
Version G5.1.10
Release Latest

Error: "You need an updated version of Firefox for this extension"

The old version 1.9.55 no longer works on the webpages.

The last update of the plugin is from August 3, 2023. That is not far from the recent Waterfox release, i wonder why it wouldn't work.

**Comment by gitthangbaby** [comment]
OK so this is not compatible even with Firefox because both Waterfox and Firefox are 102.14 (choco) while the addon's requirement is 109. You need to either switch to [rapid](https://support.mozilla.org/en-US/kb/choosing-firefox-update-channel) firefox channel or:
1) go to about:config
add extensions.checkUpdateSecurity=false
add extensions.checkCompatibility.102=false
restart browser
2) click on "Download file"
edit manifest.json with strict_min_version=102
repack and install (double click)

both options work.

**Comment by rarous** [comment]
We are transitioning to Manifest v3, so there will be requirements to use recent browsers to work properly.
