### ISSUE TITLE
0divná za stejný produkt SNZB-03 u ALZA (249,- sleva 16%) a MIRONET (164,- sleva 0%)?

### ISSUE THREAD

**Issue by pokornyIt** [theodik/hlidac-shopu#1516]
Asi by stálo za to, doplnit hledání dle produktového čísla, v tomto případe **SNBZ-03**. 
U jednoho dodavatele vedete slevu 0% při ceně 164 Kč
https://www.mironet.cz/sonoff-snzb03-senzor-pohybu-zigbee+dp595456/
![image](https://github.com/topmonks/hlidac-shopu/assets/8665714/461813fa-671e-4bbc-806e-7ed5e6ba6924)
https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.mironet.cz%2Fsonoff-snzb03-senzor-pohybu-zigbee%2Bdp595456%2F

U druhého vedete na stejný produkt 16% sleva při ceně 249 Kč
https://www.alza.cz/sonoff-snzb-03-zigbee-motion-sensor-no-battery-d6884883.htm
![image](https://github.com/topmonks/hlidac-shopu/assets/8665714/3fa0310a-2bf5-4ec3-bf8a-5376508df575)
https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.alza.cz%2Fsonoff-snzb-03-zigbee-motion-sensor-no-battery-d6884883.htm

Uvedené disproporce nedávají moc důvěry v jinak výborný produkt.

**Comment by rarous** [comment]
Díky, my neporovnavame ceny mezi e-shopy, ale ukazujeme historický vývoj ceny produktu na daném e-shopu a pak vyhodnocujeme reálnost udávané slevy.

**Comment by pokornyIt** [comment]
Díky za vysvětlení. To byla moje chyba pochopení funkce. Issue je možné zavřít.
