### ISSUE TITLE
EVA_cz vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1560]
RequestError: Stream closed with error code NGHTTP2_REFUSED_STREAM
Log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/Mjxf4bmAzqeo4cfCd/runs/ZgsYJmDTalI8hWf7v#log

**Comment by rarous** [comment]
One time glitch
