### ISSUE TITLE
Rozsirenie v Safari nefunguje po update na MacOS Sonoma

### ISSUE THREAD

**Issue by bpelech** [theodik/hlidac-shopu#1632]
- Safari Version 17.0 (19616.1.27.211.1)
- Rozsirenie verzia 1.9.44
- na Alza.sk nevidno ziadny graf ani nic co tam extension pred updatom na Sonomu pridaval
- vsetky povolenia pre extension aj web stranku alza.sk su zapnute

**Comment by bpelech** [comment]
Zaujimave, ze na tychto SK weboch rozsirenie funguje:
- datart.sk
- mall.sk
- Mountfield.sk
- AAAAuto.sk
- Obi.sk

Ale na tychto nefunguje:
- alza.sk
- okay.sk
- iTesco.sk (na tejto stranke mi ani neponuklo pouzit extension - ikona v liste safari je seda a ked na nu kliknem, tak vidim klasicky prehlad o extension namiesto otazky "The extension “Hlídač Shopů” would like to access example.com.")
- Notino.sk
- Pilulka.sk

**Comment by bpelech** [comment]
pripustam aj moznost, ze problem nesuvisi s updatom na Sonomu, ale postrehol som nefunkcnost az teraz

**Comment by keson3948** [comment]
Zdravím, též mi v safari HlídačShopů funguje jen na některých eshopech.

**Comment by mhaluska** [comment]
> pripustam aj moznost, ze problem nesuvisi s updatom na Sonomu, ale postrehol som nefunkcnost az teraz

Alza mi nefungovala v Safari uz pred Sonomou. Taktez mi to nejede na iPhone a iPad - iOS 17.0.3 i predchozi iOS 16.

**Comment by salax** [comment]
Vydal jsem novou verzi, takže třeba Alza na desktopu už by měla jít. Budu pak muset ještě zkontrolovat ostatní shopy a to i v mobilnim rozlišení.

**Comment by mhaluska** [comment]
@salax diky, overeno na Macu a jede to v poradku.
