### ISSUE TITLE
rozdilna bezna cena czc/alza 

### ISSUE THREAD

**Issue by martin-hulka** [theodik/hlidac-shopu#1678]
stejna televize, ruzna bezna cena podle hlidace...

https://www.alza.cz/55-tcl-55c735-d7093488.htm?evt=ac
https://www.czc.cz/tcl-55c735-139cm/342493/produkt

![image](https://github.com/topmonks/hlidac-shopu/assets/148529831/50c8eb0f-b182-4479-8fc5-327856f987b4)

![image](https://github.com/topmonks/hlidac-shopu/assets/148529831/f08e5ce7-aaad-4970-bd6a-3e6d2fcf6f47)

**Comment by rarous** [comment]
@martin-hulka Běžná cena se počítá jako cena, za kterou se zboží na daném e-shopu prodávalo nejčastěji za posledních 90 dní. Viz [naše metodika](https://www.hlidacshopu.cz/metodika/). 

Neděláne srovnávání cen mezi různými e-shopy, jen pracujeme s historií cen konkrétního zboží na konkrétním e-shopu. Pokud chcete mít srovnání s jinými e-shopy, použijte naše další rozšíření **Porovnání cen** ([Chrome](https://chrome.google.com/webstore/detail/porovn%C3%A1n%C3%AD-cen/jmhkgcmmgjblnkjkbgjggkaeifacakgi?hl=cs), [Firefox](https://addons.mozilla.org/cs/firefox/addon/porovnani-cen-by-topmonks/)).
