### ISSUE TITLE
Notino_cz/sk vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1705]
od včera (25.10.)
log cz: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/8jIanA0LXgjCGYFZd/runs/JaFHQfm9LiE9KRcev#log
log sk: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/tMWgZrDQ5baq0TxDY/runs/8b0i4pwJudqZIWiVS#log

**Comment by rarous** [comment]
Fixed in f5ae1c120f480c2390c34141d837eba022a59920
