### ISSUE TITLE
Alza_cz/sk_BF vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1711]
https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/5aEGwhWOyr0c9f3dG/runs/jFzUcTmDmexVtkjXg#log

**Comment by rarous** [comment]
Fixed in https://github.com/topmonks/hlidac-shopu/commit/cc679d13e9840cb267b756078ff05a6bae3876e6
