### ISSUE TITLE
Okay_cz_browser - v ca polovině dnů vrací 0 items 

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1712]
Podle mě se nenačte sitemap.
https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/411zYFsj9cTLuJJc1/runs
Plus si nejsem jistá, jestli na tomto actoru můžu postavit scrapování BF (https://www.okay.cz/pages/blackfriday)?

**Comment by rarous** [comment]
Okay občas na sitemap.xml vrací 500. Řešením je spustit ručně znovu po nějaké době, pokud vůbec řeší, že jim to padá.

Tento aktor ještě není na Black Friday připravený, přidám ho do backlogu.
