### ISSUE TITLE
Waterfox G6.0.5 - nefunguje graf 

### ISSUE THREAD

**Issue by Losinsky** [theodik/hlidac-shopu#1720]
Ve Waterfox G6.0.5 nefunguje graf ani v alza.cz, czc.cz atd...

**Comment by rarous** [comment]
Waterfox není námi oficiálně podporovaný a ani není v našich silách udržovat podporu pro forky forků. Generujeme zpětně kompatibilní JavaScript pro Firefox 56. Pokud ho ale nepodporuje některá z našich závislostí na úrovna APIs - například ChartJS pro kreslení grafů - nemůžeme tady sloužit. Pokud máte čas a chuť to nějak vyřešit, přijímáme Pull Requesty.
