### ISSUE TITLE
Rozdíl cen graf vs eshop Mironet

### ISSUE THREAD

**Issue by filas13** [theodik/hlidac-shopu#1740]
Dobrý den,
můžete mi prosím vysvětlit, proč se na Vašem grafu zobrazuje nižší cena, než je inzerovaná na eshopu?

https://www.mironet.cz/tineco-floor-one-s5-extreme-modra-aku-tycovy-vysavac-08-l-78-db-35-min+dp618034/

[https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.mironet.cz%2Ftineco-floor-one-s5-extreme-modra-aku-tycovy-vysavac-08-l-78-db-35-min%2Bdp618034%2F](url)

**Comment by rarous** [comment]
Dobrý den, omylem jsme minulý týden začali v extenzi načítat cenu bez DPH, oprava čeká na schválení.

**Comment by rarous** [comment]
Oprava je ve verzi 2.1.3
