### ISSUE TITLE
DM_všechny země - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1750]
podle mě nefunguje ten odkaz https://content.services.dmtech.com/rootpage-dm-shop-cs-cz/?view=navigation&json
log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/3VmmKFicqbs0K7tTd/runs/RCfwKx8hGBeHQ6aEg#log

**Comment by rarous** [comment]
DM přestalo akceptovat parametr `json` v URL a začalo na něm padat. Odebral jsem ho.
