### ISSUE TITLE
Ikea (cz/sk + všechny další země) - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1787]
cz log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/m0y6biaPNjkVMFLEZ/runs/r7fjFDiUDpOEte4in#log

**Comment by rarous** [comment]
Fixed with ba98a721ec4abf10d8b92b310f3158774df714da
