### ISSUE TITLE
Albert_cz - nový scraper + extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1886]
https://www.albert.cz/online
mělo by stačit brát info z listingu

kromě obvyklých
- currentPrice
- originalPrice
- discounted
navíc scrapovat ještě
- currentUnitPrice
- ?? originalUnitPrice ?? nikde jí nevidím uvedenou, asi budu muset dopočítávat
- useUnitPrice (true/false)
- pokud budeme originalUnitPrice dopočítávat, potřebuju scrapovat ještě hmotnost/objem

Logiku useUnitPrice bych nastavila podle "cca XY g" resp "cca XY Kč"
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/ed8c4b2a-6449-45d1-bade-ce33058c7a6a)

**Comment by rarous** [comment]
Scraper běží, data jsou dostupná na webu. Extenze je připravená k releasu.
