### ISSUE TITLE
Penny_cz - nový scraper + extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1887]
https://www.pennydomu.cz/
- uvádí unitPrice bez ohledu na měnící se váhu zboží - takže asi není nutné rozlišovat mezi Price a unitPrice
- vše potřebné je v listingu, není nutné chodit na detail produktu (je tam navíc akorát obvyklá váha zboží)

originalPrice
- ne všude mají min30back, takže pokud mají min30back, tak brát tu, jinak originalPrice
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/e13fe234-1687-474c-b725-65c5a6ba44dd)

**Comment by rarous** [comment]
`itemId` není v URL, jako slug použít část za prvním lomítkem

**Comment by rarous** [comment]
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/x7E0AGozaGwiNYDmi/information/latest/readme

**Comment by rarous** [comment]
Scraper běží, data jsou dostupná na webu.

**Comment by vaclav-slavik** [comment]
Extenze je připravená k releasu. Prosím o sanity check @rarous (je nezbytné posílat i `originaPrice` jako třeba u Alberta)?

**Comment by rarous** [comment]
@vaclav-slavik Extenze posílá data ze stránky, jako aktuální scrape, který se pro daný den cachuje. Pokud shop nikdy neuvádí `originalPrice` není potřeba ji posílat.

Penny asi nemusí dědit z `AsyncShop`. Myslím, že postačí jen `Shop`. `AsyncShop` používá `MutationObserver` kvůli shopům, které mají clinet side rendering. Penny je renderovaný na serveru a každá stránka je synchronní navigace.

**Comment by vaclav-slavik** [comment]
@rarous fixnuto dle požadavků...
