### ISSUE TITLE
Billa_cz - nový scraper + extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#1888]
https://shop.billa.cz/

sleva = Billa cena
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/15f59400-9cc9-407f-b966-16a526f67a24)

mají i klubové ceny, ty prosím ignorovat
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/a4bded57-5d37-4942-bb5e-cac48307fa21)

kromě obvyklých
- currentPrice
- originalPrice
- discounted
navíc scrapovat ještě
- currentUnitPrice
- ?? originalUnitPrice ?? nikde jí nevidím uvedenou, asi budu muset dopočítávat
- useUnitPrice (true/false)
- pokud budeme originalUnitPrice dopočítávat, potřebuju scrapovat ještě hmotnost/objem

Logiku useUnitPrice bych nastavila podle "cca XY g" resp "cca XY Kč"
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/8f9a3b9d-3923-4d5a-a9d3-e958e3bae419)

**Comment by rarous** [comment]
Přidán scraper v a1de5b1bfdd6aec0405f0eea26e099d8d9f1da60

**Comment by rarous** [comment]
@MartinaGelnerova `itemId` je v URL a lze použít jako slug.

**Comment by rarous** [comment]
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/I6VZOgaOruqjvtE2u/information/latest/readme

**Comment by rarous** [comment]
Scraper běží, data jsou dostupná na webu. Extenze je implementovaná na detailu produktu, pro popup se musí doimplemenovat stavový automat.
