### ISSUE TITLE
Nefunguje vývoj ceny u produktů na allegro.cz

### ISSUE THREAD

**Issue by Piskvor** [theodik/hlidac-shopu#1998]
Očekávané chování na webu:

1. otevřu hlidacshopu.cz
2. zadám https://www.allegro.cz/nabidka/lego-icons-10328-kytice-ruzi-14980356066 nebo https://allegro.cz/nabidka/lego-icons-10328-kytice-ruzi-14980356066
3. vidím graf

Skutečné chování:

3. "Nenalezeno
Je nám líto, ale hledaný produkt nebo e-shop nemáme v naší databázi.
Podporované e-shopy
...[Allegro.cz](https://www.allegro.cz/)..."

Rozšíření se chová stejně - jako by Allegro nebylo v podporovaných shopech. Stejně se chovají i další produkty na allegro.cz. Zkoušeno v různých prohlížečích (s jinými rozšířeními i bez, vč. private módu), stejné chování všude.

**Comment by rarous** [comment]
Allegro je podporováno pouze v Dashboardu. Měli jsme v plánu mít plnou podporu i v extenzi, ale zvedlo nám to náklady na provoz 10x. Pro nás je to neudržitelné. Omlouvám se za zmatení, logo z webu sundám.
