### ISSUE TITLE
Viditelna hlaska, pokud nemam historicky data

### ISSUE THREAD

**Issue by Masa331** [theodik/hlidac-shopu#2]
Pokud navstivim produkt, pro ktery nemam historicky data(z elasticu se vrati prazdne), tak se mi v tele grafu zobrazi nejaka hlaska typu "Pro tento produkt nemame data". Aby bylo jasne, ze to neni rozbity ale jen to neni nascrapovany

**Comment by theodik** [comment]
33669617e66cd36ea9e17fab9ef26818996710bb
