### ISSUE TITLE
Okay_cz vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2019]
https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/411zYFsj9cTLuJJc1/console

**Comment by rarous** [comment]
@MartinaGelnerova zkoukni prosím data, scrape už by měl jet

**Comment by MartinaGelnerova** [comment]
@rarous scrape běží, ale už běží přes 4 hodiny - nešlo by to optimalizovat?
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/411zYFsj9cTLuJJc1/runs/NbinXYFOHOrekTmGv#log

Nevidím v datech žádné zlevněné items - namátkově jsem vzala zlevněný produkt, a ten je v datech jako nezlevněný (discounted=false + originalPrice=null). OriginalPrice je uvedená jenom na detailu produktu, v category listingu originalPrice neuvádějí.
https://www.okay.cz/products/rychlovarna-konvice-gorenje-k17cli-bila-1-7l
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/f2be3132-d405-45cc-b5a2-17eff2a730e8)
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/42549a69-baf5-408d-90ea-e9bc405404a7)
https://www.okay.cz/collections/tyden-gorenje-hisense-se-slevou-az-25-na-male-spotrebice
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/3d0acd93-f1a2-4fbd-a44c-3be5c3337b85)

Mohl bys na to prosím ještě kouknout?

**Comment by rarous** [comment]
Detaily se nescrapuji, běží ti celý v browserů, kvůli tomu vizuálnímu schovavani cen. Proto je to tak pomalý.

**Comment by MartinaGelnerova** [comment]
currentPrice jede dobře, originalPrice nebereme ... zavírám issue
