### ISSUE TITLE
Ignorované klubové karty ?

### ISSUE THREAD

**Issue by eltomjan** [theodik/hlidac-shopu#2168]
Všiml jsem si, že třeba u iTesco ignorujete slevy s CC, které jsou dost podstatné - proč ?

**Comment by rarous** [comment]
Na klubové karty se Evropská směrnice neztahuje, pouze na plošné slevy. Ani není v našich silách registrovat se do všech možných klubů a zjišťovat, který uživatel v jakém klubu je.

Naším cílem je mít historii cen, za které se produkt reálně prodával, vůči které si kdoliv může porovnat jak realná je jakákoliv sleva.

**Comment by eltomjan** [comment]
Díky, pak ale sledujete ceny, které jsou vcelku bezcenné :-)
Krom lidí, kteří mají problém s internetem (registrací), zapomenou kartu nebo možná turistů snad nikdo neplatí o desítky procent vyšší ceny, které sledujete.
