### ISSUE TITLE
Lidl_cz - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2267]
asi změna struktury stránky, protože v logu vidím:
`Found 0x categories in https://www.lidl.cz/c/kategorie/s10004543`

log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/RS4d571fc6LANBU3X/runs/Zc1L7dVldaw5muV9B#log

**Comment by rarous** [comment]
Problém byl ve změně selektoru.

@MartinaGelnerova zkontroluj prosím dat, mělo by být optaveno.

**Comment by MartinaGelnerova** [comment]
@rarous data v pořádku, scrapujeme výrazně víc produktů než před problémem (1.100 => 4.900).
Díky za opravu, zavírám.
