### ISSUE TITLE
DM_cz/sk - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2268]
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/3VmmKFicqbs0K7tTd/runs/nNnS7TaWa1ZTk9yLH#log

**Comment by rarous** [comment]
@MartinaGelnerova Teď běží opravený CZ run, mrkni pak na výsledky, že jsou ok

**Comment by rarous** [comment]
Data už se scrapují, problém byl ve změně struktury dat.

Vypadá to, že tam mají rate limiter, který nebereme v potaz.

**Comment by MartinaGelnerova** [comment]
@rarous data v pořádku, díky.
Občas se mi nevykreslí extenze, přitom data Hlídače jsou na stránku načtený, např tady:
https://www.dm.cz/trend-t-up-ocni-stiny-n-1-117-p4058172945755.html
https://www.dm.cz/seinz-hydratacni-pletovy-fluid-p4066447410778.html
Podle mě to shazuje tenhle error, protože někdy pomůže reload stránky a error zmizí a extenze se vykreslí
![image](https://github.com/topmonks/hlidac-shopu/assets/82106162/3b7a1822-42d1-4977-849a-0c8de5e21cf4)

**Comment by rarous** [comment]
Je tam race condition - jiná issue
