### ISSUE TITLE
mall.cz

### ISSUE THREAD

**Issue by MNtesx** [theodik/hlidac-shopu#2433]
Dobrý den,
mall.cz ukazuje v grafu zdražení od aktuálního dne přitom zboží už je několik dní zdražené.

příklad, kdy zboží už 4.9 bylo za aktuální cenu, ale graf ukazuje, že ještě bylo za tu sníženou.

https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.mall.cz%2Fsvetla-kolo%2Fsigma-set-svetel-buster-800-buster-rl80%3Futm_source%3Dzbozi.cz%26utm_medium%3Dcse%26utm_campaign%3DNA%26utm_content%3Dsvetla-kolo%26utm_term%3D26537646%26sznaiid%3D7410114920590168524%26sznclid%3DECMnJiIpICYmICYhISMlIiEjJiY

**Comment by MartinaGelnerova** [comment]
Děkuji za upozornění, mall.cz máme data z feedu, provedeme tedy nějaký check data quality.

**Comment by MartinaGelnerova** [comment]
Ještě koukám, že problém byl v období migrace Hlídače do GCP, která se bohužel roztáhla na téměř týden. Možná bylo zpoždění dat způsobené tím. Nicméně kvalitu dat prověříme.

**Comment by MartinaGelnerova** [comment]
Aktuálně v datech toho konkrétního produktu vidím slevu 1.9. a 2.9., od 3.9. už cenu vyšší - takže to opravdu vypadá na zpoždění dat.
![image](https://github.com/user-attachments/assets/8ae52433-88a5-4f89-b628-071f888af270)
