### ISSUE TITLE
Lidl nezobrazuje graf

### ISSUE THREAD

**Issue by McMajlos** [theodik/hlidac-shopu#2483]
Tak chyba bude na mé straně nebo na straně Brave prohlížeče. 

Graf je zobrazen asi na 0,5 vteřiny při loadu stránky. Poté zmizí. Asi ho Brave blokuje. Zajímavé je, že na alza.cz zůstane...

Ačkoliv je uvedeno, že stránka lidl.cz je podporovaná, tak se nezobrazuje graf jako např. na alza.cz. Např na tomto odkazu: https://www.lidl.cz/p/silvercrest-kitchen-tools-mikrovlnna-trouba-smwh-700-b2-sedohneda/p100375241

**Comment by rarous** [comment]
Spíše to bude špatný časování vkládní našeho grafu. Asi ho vkládáme dřív, než se Lidl ustálí. Nebo ho začali aktivně schovávat.

**Comment by rarous** [comment]
Řešíme v #2540
