### ISSUE TITLE
CZC_cz - nově pod Allegro.cz => potřebujeme scraper pro https://czc.cz/

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2491]
Asi by to šlo vyřešit zároveň scraperem pro Allegro.cz, který ale aktuálně nefunguje viz https://github.com/topmonks/hlidac-shopu/issues/2338

**Comment by MartinaGelnerova** [comment]
@HamzaAlwan could we please solve this with Allegro scraper?
Czc.cz has been taken over by Allegro, the page has now Allegro design. I would need full crowl and scrape within https://allegro.cz/obchod/czc-cz

**Comment by HamzaAlwan** [comment]
@MartinaGelnerova, I add support https://allegro.cz/obchod/czc-cz inside the allegro daily Actor in this [pull request](https://github.com/topmonks/hlidac-shopu/pull/2619)

**Comment by MartinaGelnerova** [comment]
@HamzaAlwan can you please help me to setup this actor properly for Hlídač shopů?
- I should build actor from [allegro](https://github.com/topmonks/hlidac-shopu/tree/trunk/actors/allegro-daily) and not from https://github.com/topmonks/hlidac-shopu/tree/trunk/actors/czc-daily, right?
- How do I properly set the input in order to crawl CZC only (and not whole Allegro)?
🙏

**Comment by HamzaAlwan** [comment]
- Yes you should build the Actor from [allegro](https://github.com/topmonks/hlidac-shopu/tree/trunk/actors/allegro-daily)
- You can scrape all categories by passing this URL: `https://allegro.cz/obchod/czc-cz` or specific categories: `https://allegro.cz/obchod/czc-cz/nabidky/pocitace-notebooky-491`

**Comment by MartinaGelnerova** [comment]
@HamzaAlwan set-up, build, scraper runs but does not return any prices - it returns items, but prices are null
Can you please have a look at it?
run log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/PVMsvz5mx6d8k7Puy/runs/kWYyQpfHZITiHe1VM#output

**Comment by HamzaAlwan** [comment]
Hey @MartinaGelnerova,

I created a new [pull request](https://github.com/topmonks/hlidac-shopu/pull/2626) which addresses the issue, here is an example [run](https://console.apify.com/actors/UXHr00dvEbrVly4BW/runs/nfYEcDN74xb8sWrmM#output).

**Comment by MartinaGelnerova** [comment]
It works now, great, thank you! Closing the issue.

**Comment by MartinaGelnerova** [comment]
@HamzaAlwan sorry, one more thing - the CZC data is being sent to allegro_cz table in Keboola. Can you please change it to table named "czc"?

**Comment by HamzaAlwan** [comment]
Hey @MartinaGelnerova,

I added a new input called `tableName`, which allows you to enter `czc`. If `czc` is provided, it will change the Kaboola table name to `czc`. It defaults to `allegro_cz` 

Here is the [pull request](https://github.com/topmonks/hlidac-shopu/pull/2632)

Example input:
```
{
  "development": false,
  "debug": false,
  "proxyGroups": [],
  "type": "FULL",
  "urls": [
    "https://allegro.cz/obchod/czc-cz"
  ],
  "tableName": "czc",
}
```

**Comment by MartinaGelnerova** [comment]
@HamzaAlwan thank you!
