### ISSUE TITLE
Albert_cz - run vrací 0 items ('PERSISTED_QUERY_NOT_FOUND')

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2492]
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/SWis54ZxTdx0UY7uM/runs/0Yah8sUclklbx7QNl#log

**Comment by oleksandravalko** [comment]
@MartinaGelnerova please review.

**Comment by MartinaGelnerova** [comment]
@rarous can you please review the commit?

**Comment by rarous** [comment]
@MartinaGelnerova merged

**Comment by MartinaGelnerova** [comment]
Works fine, thanks for the fix. Closing the issue.
