### ISSUE TITLE
Notino_cz - špatné ceny u produktů s kódem

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2499]
př: https://www.notino.cz/makeup-revolution/xmass-2024-advent-calendar-adventni-kalendar/
![image](https://github.com/user-attachments/assets/da911410-668a-4f6e-abd4-ee65a3b02a56)

správné hodnoty: currentPrice 1386, originalPrice 1540
actor vrací: currentPrice 1540 (tj cenu bez kódu), originalPrice null (ignoruje "Minimální cena")
extenze vrací: currentPrice 1540 (tj cenu bez kódu), originalPrice 1386 (tj cenu s kódem => správně "Minimální cena")

**Comment by MartinaGelnerova** [comment]
@valekjo is taking look into this

**Comment by MartinaGelnerova** [comment]
@rarous pls merge

**Comment by rarous** [comment]
@MartinaGelnerova please build&check :)

**Comment by MartinaGelnerova** [comment]
works just fine, closing the issue

**Comment by MartinaGelnerova** [comment]
@valekjo please correct originalPrice - in case "Minimální cena" is present (not always is), preferable use this as originalPrice
example: https://www.notino.cz/artdeco/color-booster-balzam-pro-podporu-prirozene-barvy-rtu/
![image](https://github.com/user-attachments/assets/0153d82f-ee68-4a83-819a-3d3faf612614)

Extension still waiting to be corrected... @vaclav-slavik

**Comment by valekjo** [comment]
@MartinaGelnerova here: https://github.com/topmonks/hlidac-shopu/pull/2610

If the recent price is present in data, we'll use it for `originalPrice` for the products with voucher discount.

**Comment by rarous** [comment]
Extension is in #2609
