### ISSUE TITLE
Pilulka_cz - vrací 0 items (sitemap.xml stránka nenalezena)

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2517]
log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/9384d5rh2Ghs5M6XN/runs/gJfHKtgn4XeMGcJkL#log

![image](https://github.com/user-attachments/assets/05e83831-666e-490d-83ce-b2d48c9d5734)

![image](https://github.com/user-attachments/assets/0cfe0b95-4402-4d2b-8201-7cf77db8f298)

**Comment by Strajk** [comment]
Sitemapu maji porad v robots, tak snad je jeji 404 jen docasna chyba

![image](https://github.com/user-attachments/assets/42549c4f-fec4-492e-ab46-076d958f69a9)

**Comment by rarous** [comment]
Spíš to smazali jako ochranu proti scrapování a zároveň nikdo neřeší, že to je i v `robots.txt`. Ukol zněl jasně, smazat `sitemap.xml`. :)

**Comment by MartinaGelnerova** [comment]
Prosím o doplnění respektování cen s kódem - příklad asi bude rychle out-dated, ale mají na to přímo kategorii v Akcích
https://www.pilulka.cz/cena-s-kodem-1
![image](https://github.com/user-attachments/assets/e897f724-23b3-4029-b297-72fd21ecb882)

př: https://www.pilulka.cz/fr2500-horkovzdusna-friteza-2-5-l
`<div data-v-b5484f66="" class="price-with-code__price notranslate">1 192 Kč</div>`
![image](https://github.com/user-attachments/assets/86600ce4-c8ae-46b5-8162-55b852432a57)

**Comment by JameEnder** [comment]
Už mám napsanej fix, ale nemám práva na push :D

**Comment by JameEnder** [comment]
Fixed, PR created :)

**Comment by MartinaGelnerova** [comment]
@rarous pls merge 🙏

**Comment by MartinaGelnerova** [comment]
Works fine, thanks for the fix.
No "code discount" at the moment, let's assume it works as well.

**Comment by Strajk** [comment]
Berou se i "ceny v aplikaci", ale to IMO dobre – filozoficky to je proste verejnej kupon s extra krokem navic.

![image](https://github.com/user-attachments/assets/bb446154-7d9f-4ffc-bd8a-cc8da3c419b7)

A obcas se nenastavuje `discounted`, nevim jestli je to dulezite.

![image](https://github.com/user-attachments/assets/0f72be8b-fb45-49b0-af55-c4ac23888496)

**Comment by MartinaGelnerova** [comment]
@Strajk "cena v aplikaci" je považována za member price, protože se předpokládá, že aplikace požaduje přihlášení. Takže nikde jinde zatím cenu v aplikaci myslím nebereme. Takže ten konkrétní produkt bych brala currentPrice=539, originalPrice=559.

Chybné označení "discounted" pro mě není důležité, důležité ale je tam mít originalPrice, což v tomto případě nemám:
![image](https://github.com/user-attachments/assets/84cb4475-e1fa-47bd-94d0-85eae8005e57). Na tom pak stojí vyhodnocení, jestli je sleva správně vyčíslená nebo ne. Měla by tem být originalPrice=869-.
