### ISSUE TITLE
Okay_cz - change currentPrice + originalPrice selectors

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2550]
**currentPrice** - the shop switched to display prices without VAT (bez dph)
=> change selector to save price incl. VAT
- in scraper
- in extension
example: https://www.okay.cz/products/roboticky-vysavac-hoover-hg510d-011
![image](https://github.com/user-attachments/assets/2c04dbd8-cc32-4313-9f77-c132c5930731)

**originalPrice**
example - "Doporučená cena výrobce" - extension saves it, but scraper does not
=> add originalPrice selector to scraper
https://www.okay.cz/products/roboticky-vysavac-hoover-hg510d-011
![image](https://github.com/user-attachments/assets/56ddf853-a18e-4cfe-92be-59840c2a61f1)
![image](https://github.com/user-attachments/assets/e9b2638a-9e1c-464a-a629-f8e7ba20a0b6)

example - "Nejnižší cena za posledních 30 dní"
=> add originalPrice selector to scraper and extension
https://www.okay.cz/products/bezsackovy-vysavac-gorenje-vcea02galwcy
![image](https://github.com/user-attachments/assets/b35c708b-006a-4b3d-bd79-111032f24dd7)
![image](https://github.com/user-attachments/assets/5af24504-2116-416b-bd13-0a1a458d0f13)

**Comment by MartinaGelnerova** [comment]
@valekjo is checking this one.

**Comment by MartinaGelnerova** [comment]
@rarous pls merge

**Comment by rarous** [comment]
@MartinaGelnerova please, build&check :)

**Comment by MartinaGelnerova** [comment]
build ✅ 
kontrola dat zítra - běží to dlouho, dneska už to nechám dojet postaru

**Comment by MartinaGelnerova** [comment]
@rarous oprava ⬆️ pls merge

**Comment by rarous** [comment]
@MartinaGelnerova please build&check :)
