### ISSUE TITLE
Alza_cz - monthly instalment mistakenly taken as actual price

### ISSUE THREAD

**Issue by jtulak** [theodik/hlidac-shopu#2598]
When I wanted to see price history for a specific product by entering the address in https://www.hlidacshopu.cz (specifically I was looking at https://www.alza.cz/apple-airpods-pro-2-generace-s-magsafe-usb-c-2022-d7927651.htm), the comparator used HomeCredit monthly instalment of 202 CZK rather than actual price 6290 CZK, computing a nice but unfortunately imaginary 96% discount. 😃 

<img width="543" alt="Screenshot 2024-11-03 at 7 54 54" src="https://github.com/user-attachments/assets/35af111f-f703-4b1f-a9e0-a348880bb728">
<img width="531" alt="Screenshot 2024-11-03 at 7 54 35" src="https://github.com/user-attachments/assets/6c0861b4-0ee7-4e79-be48-6c855f2a5f8e">

**Comment by MartinaGelnerova** [comment]
@vaclav-slavik this is problem of selector on extension side, please check and correct

**Comment by MartinaGelnerova** [comment]
solved, closing the issue
![image](https://github.com/user-attachments/assets/e752874d-d260-444f-a00b-08c9ae59f359)
