### ISSUE TITLE
Extension - 100% discount when currentPrice not found by the extension

### ISSUE THREAD

**Issue by wheder** [theodik/hlidac-shopu#2599]
Showing 100% discount when no discount is actually present.

And 100% discount should mean this item is completely free ... which is not.

https://www.obi.cz/lazury-na-drevo/balakryl-interierovy-lak-na-drevo-sportakryl-matny-0-7-kg/p/1105899

![image](https://github.com/user-attachments/assets/f0c5b57f-bf4b-42d4-89d1-c21671e2be9e)

**Comment by MartinaGelnerova** [comment]
Another example: https://www.hlidacshopu.cz/?url=https%3A%2F%2Fwww.pilulka.cz%2Fmagnesium-b6-bisglycinat

This happens when extension does not find currentPrice...
@rarous
