### ISSUE TITLE
Alza_cz - extension not visible for specific product (Cannot read properties of null (reading 'innerText'))

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2603]
https://www.alza.cz/lg-f2dv5s8s1-d6153071.htm
![image](https://github.com/user-attachments/assets/76869781-7edc-41fd-83d8-142a89545880)

**Comment by donny85** [comment]
```
const title = document.querySelector('h1[itemprop="name"]').innerText.trim();
```
Bad selector, the `<h1>` doesn't seem to have `itemprop` property anymore. It works with `#detailItem h1`.

**Comment by MartinaGelnerova** [comment]
Solved, closing the issue
