### ISSUE TITLE
Alza_cz nefunguje graf

### ISSUE THREAD

**Issue by Losinsky** [theodik/hlidac-shopu#2614]
Nezobrzuje se graf ode dneška

**Comment by fanick1** [comment]
@Losinsky - v releasech v nejaktualnejsi verzi (2.1.10) uz je to -zda se- opraveno. Na chrome webstoru je ale porad stara verze.

**Comment by Losinsky** [comment]
Na Firefox (používám) storu je stále verze 2.1.8. V klidu počkám...

**Comment by MartinaGelnerova** [comment]
Chrome už funguje. @vaclav-slavik jak je na tom Firefox?

**Comment by Losinsky** [comment]
Ve Firefoxu je dostupná stále jen stará verze 2.1.8
Je to normální, že to tak dlouho trvá?

**Comment by vaclav-slavik** [comment]
Díky za report. Publishing nových verzí FF extenze je v řešení a v budoucnu by měl fungovat automaticky vždy s releasem nové verze extenze.

**Comment by vaclav-slavik** [comment]
@Losinsky 
> Ve Firefoxu je dostupná stále jen stará verze 2.1.8 Je to normální, že to tak dlouho trvá?

Nová verze 2.1.10 pro FF je venku. Díky za trpělivost!

**Comment by rarous** [comment]
Release FF verze je bohužel ruční proces a automatizace není možná - je pro nás blokovaná. Automatizovaný je pouze build balíčku extenze, který se pak ručně zadává k nasazení.
