### ISSUE TITLE
Mironet_cz BF task - returning 0 results - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#2655]
run log: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/9ksq5Uah7layZnrWs/runs/OoRBRhZ2eEhzyyL0g#log

**Comment by oleksandravalko** [comment]
@MartinaGelnerova please have a look. 
1. Url for BlackFriday was https://www.mironet.cz/vyprodej/?v=**blue**-friday;
2. Layout for sale event is a bit different, so I edited selectors and removed logic, that doesn't make sense anymore.
3. Pagination now looks different as well, so I changed selectors.

**Comment by MartinaGelnerova** [comment]
@rarous please check and merge 🙏

**Comment by MartinaGelnerova** [comment]
@oleksandravalko for the future, could we add BF start URL to the input, so it can be changed easily?

**Comment by MartinaGelnerova** [comment]
works fine, thanks @oleksandravalko for the fix, closing the issue
