### ISSUE TITLE
Alza - chybná sleva 96 procent

### ISSUE THREAD

**Issue by Pecicek** [theodik/hlidac-shopu#293]
Na [tento](https://m.alza.cz/tp-link-tapo-c200-d5703789.htm)  odkaz byla vypočítána sleva 96 procent z částky 899 Kč... Výsledná cena tedy 35 Kč. Alza ale na tento produkt slevu nemá a stojí normálně 899 Kč

**Comment by rarous** [comment]
Dobrý den, 16. ledna jsme měli na Alze špatný scrape dat. Data pročišťujeme a připravujeme monitoring podezřelých změn.
