### ISSUE TITLE
Nezmyselne hodnoty pri niektorych SK tovaroch 

### ISSUE THREAD

**Issue by marekmichalik** [theodik/hlidac-shopu#300]
Grafy niektorych tovarov vykazuju anomaliu, akoby tam k cene v EUR bola dotiahnutá pred par dnami cena v CZK.
Graf je potom cely stlaceny k x-oxej osi a stráca výpovednú hodnotu. Napr.: https://www.alza.sk/sport/city-boss-gv4-cierna-d5874870.htm
Velmi vam fandim, nech sa dari,
m.
![image](https://user-images.githubusercontent.com/34522046/104969286-4df33000-59e8-11eb-9ae6-ffe44fee3bd0.png)

**Comment by rarous** [comment]
Dobrý den, 16. ledna jsme měli na Alze špatný scrape. Data pročišťujeme a připravujeme monitoring podezřelých změn v cenám.
