### ISSUE TITLE
Delší historie vývoje cen (ideálně od uvedení na trh)

### ISSUE THREAD

**Issue by tprochazka** [theodik/hlidac-shopu#397]
Někdy by se strašně moc hodilo vidět celou historii ceny až po uvedení na trh, ani ne tak přímo na stránkách eshopu, ale až když se pak prokliknu k vám na web.

**Comment by rarous** [comment]
Ukazujeme vždy kompletní historii cen, co máme.

**Comment by tprochazka** [comment]
Aha, mě to přišlo ořezané, možná jsem se díval na nějakou variantu téhož produktu, která byla novější. Omlouvám se.

**Comment by rarous** [comment]
Scraping není 100%. Navíc různé shopy byly zapojeny v různou dobu. Technicky nemůžeme mít data starší než, kdy jsme začali scrapovat.
