### ISSUE TITLE
Extension spamuje konzolu

### ISSUE THREAD

**Issue by fczbkk** [theodik/hlidac-shopu#500]
Rozšírenie spamuje konzolu. Vytvorí si `console.group`, vypíše do nej číslo verzie a potom tú grupu nezatvorí. Toto je kus kódu, ktorý to spôsobuje:

<img width="415" alt="Screenshot 2021-03-17 at 14 30 42" src="https://user-images.githubusercontent.com/43734/111475525-728c2f80-872d-11eb-9db2-e707e870e76f.png">

Osobne tam vidím dva problémy: Jednak to, že to niečo vypisuje do konzoly. Imho by to malo robiť iba na vyžiadanie, v nejakom debug móde. Ale hlavne, keď už si to tam vytvorí grupu, tak by ju to malo aj zatvoriť. Pretože inak to zbytočne komplikuje život vývojárom, ktorí tam potrebujú debugovať niečo iné.

<img width="579" alt="Screenshot 2021-03-17 at 14 29 16" src="https://user-images.githubusercontent.com/43734/111475540-77e97a00-872d-11eb-9cc5-68ff01d5bb1b.png">

**Comment by rarous** [comment]
Groupa zrušena :)

**Comment by fczbkk** [comment]
<img src="https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif">
