### ISSUE TITLE
Hodně matoucí plná čára v grafu pro chybějící data

### ISSUE THREAD

**Issue by jakubbalada** [theodik/hlidac-shopu#534]
<img width="523" alt="Screen Shot 2021-04-14 at 18 28 13" src="https://user-images.githubusercontent.com/14894832/114745815-58a33400-9d4f-11eb-927d-0a83e35e1ba2.png">
https://www.alza.cz/samsung-ar12txhqasineu-samsung-ar12txhqasixeu-vc-instalace-d5865555.htm

Tady máme poslední data z 15.1. a k přecenění podle Alzy došlo 13.4.

Obecně někde v grafu chybějící data znamenají přerušenou čáru, jinde plnou (k aktuálnímu dni).

Chtělo by to buď všude nedoplňovat čáru, když chybí data, nebo udělat přerušovanou.

**Comment by rarous** [comment]
Při přidávání data pointu z extenze se musíme podívat na poslední záznam z DB. Pokud má `null` musí přidat ještě jeden `null` chvíli před aktuálním data pointem.
