### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by MatejPetrik007** [theodik/hlidac-shopu#548]
Dobrý den, zmyzel addon z je možnost poslat - poskytnout, když jsem skoušel zip z gitbuhu ukazuje že soubor je poškozen
![obrázok](https://user-images.githubusercontent.com/67949791/116216376-d94b3280-a748-11eb-8d40-278026f14ca9.png)
![Bez názvu](https://user-images.githubusercontent.com/67949791/116215823-51652880-a748-11eb-80d4-029feb755c6b.png)
děkuji

**Comment by rarous** [comment]
Dobrý den, proces review s Mozillou řešíme. Připravujeme i publikování release verze balíčků s extenzí, zde na Githubu. Prozatím se dá aktuální verze [stáhnout z našeho CI serveru](https://8696-159496161-gh.circle-artifacts.com/0/dist/firefox-extension-1.8.20.zip). Bohužel není podepsaná pro distribuci, protože to vyžaduje stejný postup, jako publikace na Addons Mozilla, kterou nám zatím pozastavili.

**Comment by MikkCZ** [comment]
Dobré odpoledne.

Vypadá to, že se to moc nepohnulo, a hlídač na AMO (addons.mozilla.org) pořád není. Kde se to zaseklo, případně můžu to zkusit nějak popohnat/zařídit lepší kontakt?

**Comment by rarous** [comment]
Problém je na review, kde nejsou schopný provést lokální build extenze ani podle návodu. Návod jsme udělali podrobnější, build zjednodušili, ale úspěchu jsme se nedočkali. :)

**Comment by MikkCZ** [comment]
Díky za info. Naklonoval jsem se repozitář, spustil po sobě `yarn install --immutable` a `yarn build:firefox` a výsledek na první pohled vypadá funkčně. Byl to správný postup?

**Comment by MikkCZ** [comment]
`jq` už jsem na PATH měl a Node mám tedy 14, ne 16.

**Comment by rarous** [comment]
Postup je tu https://github.com/topmonks/hlidac-shopu#step-by-step-build-of-extension-for-reviewers :)

**Comment by rarous** [comment]
Budeme připravovat nový build a dělat novou submission, snad budeme mít větší štěstí na reviewera.

**Comment by rarous** [comment]
Nový release najdete zde: https://github.com/topmonks/hlidac-shopu/releases/tag/extension-1.9.0

**Comment by MikkCZ** [comment]
Pořád stále stejný problém? Zkusil jsem se přeptat na Matrixu, ale veřejně to neprobírají. Nicméně zkuste napsat do místnosti _#addon-reviewers:mozilla.org_, třeba tam dostanete nějaký přímější kontakt a vyřešíte to rychleji než po mailu nebo komentáře skrze AMO.

**Comment by MikkCZ** [comment]
Vidím, že nic nevidím. Nastává pro mě čas střídavých dovolených a nebudu mít zas až tolik času. I kdyby bylo do konce prázdnin něco, s čím můžu pomoci, tak bohužel...

**Comment by Stepan-H** [comment]
Dobrý den,
stále není addon na addons.mozilla.org . Bylo by možné vytvořit build pro Běžné Franty Uživatele?

Je sice hezké, že máte návod jak udělat build, ale:
Co je to Node.js 16? Co je to yarn? Kde to najdu? Jak to nainstaluji nebo to instalovat nemusím? Je to vůbec možné spouštět ve Windows? Kam píšu tu sekvenci příkazů, do příkazového řádku Windows nebo v nějaké té aplikaci, kterou bych měl mít? ... a dalších milión BFU otázek.

Prosím o vytvoření buildu, který by se dal stáhnout a otevřením ve Firefox nainstalovat.
Děkuji.

**Comment by rarous** [comment]
@Stepan-H buildy jsou zde v sekci Releases: https://github.com/topmonks/hlidac-shopu/releases/tag/extension-1.9.1

**Comment by rarous** [comment]
Jen poznámka k aktuálnímu stavu:

Už jsem byl schopný napsat návod, který reviewer zvládl replikovat. Ztroskotalo to na code review, kde kontrolují kód, který je sdílený mezi extenzí a webem a vadily jim dynamické importy, které se používají na webu pro polyfillování starého Safari, ale v extenzi nejsou. Už jsem neměl čas vysvětlovat jak funguje treeshaking a že kód, který se ve výsledném kódu nevyskytuje není třeba řešit.

**Comment by Haldyz** [comment]
Taky bych prosil o navod, jak aktualni release nainstalovat do FF ve Windows. Diky

**Comment by MilosHavranek** [comment]
Zítra to bude již 4 měsíce od založení issue.

Pokud by byl problém ohledně buildů, tak je nejjednodušší vytvořit Dockerfile, kde může provést build i někdo, kdo vůbec nemá nodejs a jiný toolchain. Evidentně toto již není třeba řešit.

Co se týče těch ostatních věcí, na kterých nyní stojí to review, tak s tím bohužel neporadím.
Zkušenost praví, že pokud něco chci, tak musím jít štěstí naproti a spolknout nachvíli svoji hrdost.

Je tedy nějaká možnost, jak vyhovět zmíněným nedostatkům v code review?

**Comment by vpil** [comment]
> 
> 
> Taky bych prosil o navod, jak aktualni release nainstalovat do FF ve Windows. Diky

1. Najděte si aktuální release zde https://github.com/topmonks/hlidac-shopu/releases
2. Stáhněte si třeba firefox-extension-1.9.2.zip
3. Přejmenujte koncovku staženého souboru na .xpi, tj. firefox-extension-1.9.2.xpi
4. Ve firefoxu napište do adresního řádku "about:config"
5. Vyhledejte a deaktivujte "xpinstall.signatures.required"
6. Přetáhněte .xpi soubor do okna Firefoxu/Waterfoxu a potvrďte instalaci

**Comment by Haldyz** [comment]
dekuji, ale vypada to, ze vypnuti kontroly podpisu funguje je mozne pouze v Extended Support Release (ESR), Firefox Developer Edition and Nightly verzich Firefoxu, v normalni to nastaveni najdu taky, ale prestoze to mam zakazane, tak to stale hlasi ze to nejde nainstalovat, jelikoz to neni podepsane :-(
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by vpil** [comment]
Tak to mě mrzí. Nenapadlo by mě, že to nepůjde ve standardní verzi. Já to ověřoval na aktuální ESR a Waterfoxu.

**Comment by MilosHavranek** [comment]
Smutné je, že hlídač shopu nefunguje na firefox už půl roku. Normální uživatel nemá možnost si jej nainstalovat. A ani my ostatní, pokud si nenainstalujeme speciální build firefoxu.

**Comment by rarous** [comment]
Ano, smutné to je. Ale podívejte se na to optikou: kolik času jsme už propálil na review procesu do Mozilla Addons, kolik uživatelů reálně Firefox používá a má naši extenzi (cca 7 % naší celkové userbase), a kolik peněz nás to stojí (dost) a přináší (0). Chápu, že to je nepříjemné, ale aktuálně máme důležitější věci na práci, než se handrkovat o jeden řádek kódu, který v extenzi ani není.

**Comment by Stepan-H** [comment]
Normálně bych se nevyjádřil, ale ten argument "kolik uživatelů reálně Firefox používá a má naši extenzi" je zcela nesmyslný. Jak to má normální uživatel používat, když to není k dispozici? 7% jsou pouze uživatelé, kteří mají vývojářský build FF. Normální uživatelé to nepoužívají, protože to nenajdou na stránce Addonů a když už o to zavadí v různých článcích na Internetu a chtějí to nainstalovat, tak nemůžou. Já jsem to chtěl také používat, ale když jsem zjistil, že bych musel mít vývojářskou verzi FF, která je mi k [autocenzura], tak jsem to vzdal...

**Comment by rarous** [comment]
Beru čísla, když se to dalo instalovat ze store. O tom, kdo si to naistaloval lokálně nemáme žádné údaje.

Existuje spousta jiných prohlížečů, které nemají problém a extenze tam funguje, případně máme web nebo aplikace do mobilů. Pokud chcete sponzorovat náš čas, který budeme muset trávit s Mozillou - s vidinou toho, že se to brzy zase rozbije (Manifest v3) - tady někde okolo je tlačítko. :)

**Comment by Stepan-H** [comment]
Tak se rozhodněte. Buď to FF podporuje nebo ne. Když to FF nepodporuje, protože máte s Mozillou problém a nechcete to řešit, protože máte něco lepšího na práci, tak mějte koule a napište "Končíme podporu FF, protože Mozilla..." a zrušte na stránkách, že podporujete FF. 

Na stránkách máte napsáno "Hlídač shopů je neziskový projekt, jehož cílem je chránit české spotřebitele ...". To si docela dost protiřečíte, viz Vaše tvrzení "Pokud chcete sponzorovat náš čas...".

**Comment by rarous** [comment]
Myslíte, že by sponzorování několika hodin rázem dostalo Hlídače do zisku? :) 

Stránky upravíme.

**Comment by MilosHavranek** [comment]
Dost času se dalo určitě ušetřit na dohadování se s FF reviewery ohledně toho, jak buildit tento doplněk. Tento čas mohl být věnován dockerizaci buildu, pak by problém odpadl a nikdo následně návod na buildění nepotřebuje. 
Zbylý čas se mohl věnovat řešením problému o jednom řádku kódu. 

Je potřeba to brát tak, že vy něco chcete po FF reviewerech, a k problému přištupovat asertivně a s nadhledem.

Nikdo kvůli jednomu doplňku nebude měnit prohlížeč. Spousta lidí FF používá pro jeho unikátnost a možnosti, které Chromium prohlížeče nenabízí. A jestli někoho baví používat Chrome, tak prosím.

**Comment by Stepan-H** [comment]
K větě "Myslíte, že by sponzorování několika hodin rázem dostalo Hlídače do zisku?"
1.) Hlídač dle vašich stránek evidentně není ziskový, takže jakýkoliv sponzoring bude zjevně více než doposud. To by ale pak Hlídač přestal být neziskový...
2.) To Vy sám píšete "Pokud chcete sponzorovat náš čas...", takže lze předpokládat, že by Vámi (nikoliv mnou) navrhovaný sponzoring něco mohl řešit.
3.) Možná, nejsem superman a neumím číst cizí myšlenky, jste tu větu položil sám sobě. Pak je ovšem na Vás, abyste si odpověděl a sám sobě se zasmál :) ...

**Comment by JanPokorny** [comment]
@rarous
> Existuje spousta jiných prohlížečů

No to je právě ten problém, neexistuje. Firefox je poslední prohlížeč který není Chrome. "Používá ho jen X% lidí a proto na něj nebudeme plýtvat prostředky" dává smysl z business hlediska, ale taktéž nám tento postup před 20 lety přinesl IE 6...

Poslal jsem PR které přidává dockerizovaný build, který tu byl zmíněn. Nevím zda to reálně pomůže při review procesu, ale nevím jak ze své pozice můžu lépe pomoct.

**Comment by rarous** [comment]
@JanPokorny já FF používám jako primární browser, taky jsem zažil éru před dvaceti lety (jako uživatel Phoenixe) a nevidím v tom žádný velký problém. Mozille utíkají jak uživatelé tak lidi. Je to smutný příběh, ale my s tím asi těžko něco uděláme.

Problém není v buildu extenze, ten jsme zjednodušili a lépe zdokumentovali, váše PR s Dockerem, třeba taky pomůže. Problém je v našem business rozhodnutí sjednotit kód webu, extenze, PWA a aktorů, abychom sdíleli co nejvíce stejné logiky, šablon a podobně. Pro nás to je velká úspora času (a peněz). Reviewerům z Mozilly dělá problém, že někde v těch zdrojácích je `iframe` (který se používá jen na webu a ve výsledném kódu extenze nikde není) a dynamicky importovaný polyfill na ResizeObserver, který je za feature checkem. Kód jsem posunuli co nejvíce do webu, aby tolik nedráždil a extenzi poslali na další review. Víc udělat nemůžeme.

Míček je těd u Mozilly, která se k review, dle jejich slov, dostane během několika týdnů.

**Comment by rarous** [comment]
Díky @janfiedler za prošťouchnutí extenze zpět do Mozilla Addons. https://addons.mozilla.org/en-US/firefox/addon/hl%C3%ADda%C4%8D-shop%C5%AF/

**Comment by JanPokorny** [comment]
Skvělá práce! 🎉
