### ISSUE TITLE
ALZA_HU - deduplikace v rámci scrapu

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#627]
@ladasnajberk @janfiedler
prosím optimalizovat, protože scrapujeme 1,1mil items => 150tis disctinct items

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous Už není aktuální, místo scrapu je feed. Uzavírám issue.
