### ISSUE TITLE
Datart.cz - nový produkt hlásí obří zdražení

### ISSUE THREAD

**Issue by janfiedler** [theodik/hlidac-shopu#637]
Pokud je přidán na obchod nový produkt bez historie cen, je uvedené nereálné obří zdražení.

[https://www.datart.cz/mobilni-telefon-apple-iphone-13-pro-max-1tb-silver-mlll3cn-a.html](https://www.datart.cz/mobilni-telefon-apple-iphone-13-pro-max-1tb-silver-mlll3cn-a.html)

![image](https://user-images.githubusercontent.com/13234075/133591734-143b7d55-042d-4127-b9ed-a21b20a7ac13.png)

**Comment by rarous** [comment]
Na webu jsou data správně https://www.hlidacshopu.cz/index.html?url=https%3A%2F%2Fwww.datart.cz%2Fmobilni-telefon-apple-iphone-13-pro-max-1tb-silver-mlll3cn-a.html
