### ISSUE TITLE
PROZDRAVI_CZ - změnili obsah stránky => udělat actor znova

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#651]
běží jen pár sekund a vrací 0 items
https://console.apify.com/view/runs/6Uiec68TuxZMR99ac

**Comment by MartinaGelnerova** [comment]
kompletně změnili obsah stránky, bude potřeba toho actora udělat znova.

**Comment by ladasnajberk** [comment]
Opravil jsem actora prozdravi.cz. Ted vraci 10223 produktu.

**Comment by MartinaGelnerova** [comment]
@ladasnajberk Děkuji. Prosím ještě upravit schema.
schema: {
            itemId: t.string, currentPrice: t.number
        }

**Comment by MartinaGelnerova** [comment]
@ladasnajberk Ještě prosím doplnit sloupec "breadCrumbs", upload do tabulky v Keboole hází error
{"message":"Some columns are missing in the csv file. Missing columns: breadCrumbs. Expected columns: itemName,itemId,itemUrl,description,img,category,currentPrice,originalPrice,discounted,breadcrumb,currency,inStock,blackFriday,breadCrumbs,date,actRunId. Please chec","status":"error","error":"csvImport.columnsNotMatch"}

**Comment by ladasnajberk** [comment]
Pretypoval jsem originalPrice a currentPrice na number. Pridal sloupec category, ze ktereho by mel uploader udelat breadCrumbs.
