### ISSUE TITLE
MALL_CZ + MALL_SK - low items count

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#681]
scrapuje nám výrazně málo produktů, od 9.10. každý den jen okolo 8tis items, expected 400tis items.

{"categories":6476,"pages":53475,"items":8859,"itemsSkipped":0,"itemsDuplicity":535,"failed":0}

Poslední log: https://console.apify.com/view/runs/UFoyPZz7sbGrcwNKQ

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous kontrolní scrape je vypnutý, jede jenom feed. Uzavírám issue.
