### ISSUE TITLE
Rohlik.cz - spatna original price (nejspis z extension)

### ISSUE THREAD

**Issue by jakubbalada** [theodik/hlidac-shopu#722]
Nesmyslna originalPrice (0.22 Kc) pro aktualni den.
Nejspis jiny problem nez https://github.com/topmonks/hlidac-shopu/issues/218
https://www.rohlik.cz/1384904-veprova-krkovice
<img width="1508" alt="Screen Shot 2021-12-03 at 22 30 16" src="https://user-images.githubusercontent.com/14894832/144675743-ec83bb37-be8e-4b15-a93b-8d61d25169e1.png">
18

**Comment by janfiedler** [comment]
Jelikož se ta nezvyklá cena už nezobrazuje, nejspíš nešlo o chybu extenze. Předtím jsem to tam viděl a cena byla v metadatech. Dalším scrapem se ta cena opravila. Buď teda vznikla chyba jen v tu chvíli při scrapu, nebo tam měli špatnou cenu.
