### ISSUE TITLE
PROZDRAVI_cz - nefunguje mi upload

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#724]
protože to hlásí
message: 'Some columns are missing in the csv file. Missing columns: breadcrumb,inStock,blackFriday...
Log s chybou: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/xLX9YWZgmvyif9GWp#/source

**Comment by janfiedler** [comment]
Fixed 0791d1a
