### ISSUE TITLE
MALL_sk - běží mnoho hodin, vrací pár stovek items a Error: We got blocked by target

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#729]
Mall_sk - běží mnoho hodin, vrací pár stovek items a Error: We got blocked by target

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous Už není aktuální, kontrolní scrape je vypnutý, běží jenom feed. Uzavírám issue.
