### ISSUE TITLE
Lekarna_cz vrací zhruba polovinu items co dříve - je to už delší dobu (od 24.11.)

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#736]
Lekarna_cz vrací zhruba polovinu items co dříve - je to už delší dobu (od 24.11.).
Distinct items = rows, dříve i teď, takže deduplikací to nebude.
Jestli třeba nezměnili strukturu webu?

**Comment by janfiedler** [comment]
Fixed a2aaede
