### ISSUE TITLE
lidl.cz

### ISSUE THREAD

**Issue by landsman** [theodik/hlidac-shopu#740]
Tento eshop se stal poměrně velkým, 
rád ho používám a zajímalo by mě, jak na tom je s praktikama slev :)

Přidáte ho prosím? 🙏

**Comment by Strajk** [comment]
Lidl je uz nekolik mesicu na Hlidaci https://github.com/topmonks/hlidac-shopu/commit/d8aa06ef6fcd4e24bd9f8a3c29ddd8a6eefa4d73

Overil jsem a funguje mi 
![image](https://user-images.githubusercontent.com/697301/147847594-f84927b8-f02d-4e41-8d51-ac30b7ccf4d8.png)

**Comment by landsman** [comment]
Mám Safari extension a nenačte se mi. Nejsem přihlášený v jejich uživatelském účtu.
Alza atd funguje ok.

https://www.lidl.cz/p/silvercrest-kitchen-tools-stolni-mixer-ssmc-600-b1/p100333916

![Screenshot 2022-01-03 at 23 27 34](https://user-images.githubusercontent.com/3184228/147987153-247ea459-ab68-432e-9db9-1d7bc513b5b8.png)

![Screenshot 2022-01-03 at 23 27 54](https://user-images.githubusercontent.com/3184228/147987213-4601225d-b67a-4a7c-b47e-520e1010a6cb.png)

**Comment by rarous** [comment]
Nejde o chybu v Safari, extenze nevkládá na této stránce ani v Chrome.

**Comment by rarous** [comment]
Graf už se na linkované stránce vkládá.

**Comment by landsman** [comment]
Potvrzuju, díky! 👏
