### ISSUE TITLE
iGlobus_cz často time-outuje

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#803]
Run buď doběhne za hodinu nebo (poslední dny toto častěji) time-outuje za 6 hodin.
Last run: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/JBP0Uul1QTwTwt7T7/runs/iiI7ncMYfYr0gyHUT

**Comment by janfiedler** [comment]
Fixed e5433da
