### ISSUE TITLE
iGlobus - vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#823]
poslední log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/JBP0Uul1QTwTwt7T7/runs/sPgOG5GUrMW6fXQbk

**Comment by junkycoder** [comment]
Globus se změnil, nově přibyl výběr obchodu (Zlín nebo Ostrava) a produkty jsou vypsané jinak. Postupně to opravuju, ale ten jejich eshop je nestabilní a když už se stránka načte, tak to trvá několik sekund. Po dokončení by měl být uzavřen i task #761.
