### ISSUE TITLE
Benu_cz - každý druhý den time-out

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#825]
Benu_cz - každý druhý den time-out (22.+26.+28.+30.03.)
poslední error log: https://console.apify.com/view/runs/TUwPjzxAiDyokzfUO

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous Teď 3 týdny bez time-outu, takže issue není aktuální. Closing.
