### ISSUE TITLE
CZC_cz - na jejich webu se mi nezobrazuje graf extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#827]
Na Hlídači vše funguje ok.

**Comment by junkycoder** [comment]
CZC změnilo svou galerii obrázku a na tom nám ext padalo.. Do budoucna by bylo fajn na to myslet, aby se nerozbila hlavní funkce jen proto, že něco ze scrapovaných informací chybí..
