### ISSUE TITLE
Hornbach_cz/sk vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#829]
Run se tváří jako success, běží jen pár sekund: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/ODO9pCdwnhV4SnB5U/runs/3H2Nfe4q8gV7MkuFI

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous už není aktuální. uzavírám issue.
