### ISSUE TITLE
Ikea_cz - nezobrazuje se extenze/graf na jejich webu

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#831]

**Comment by MartinaGelnerova** [comment]
@janfiedler mě se extenze na webu Ikea.cz pořád nezobrazuje

**Comment by janfiedler** [comment]
@MartinaGelnerova  ale ne z důvodu, že by to nebylo opravené, jen nemáš nasazenou novou verzi extenze. Kvůli tomu znovu otvírat issue podle mě není třeba.
