### ISSUE TITLE
Ikea_cz - scrape nebere originalPrice

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#832]
V datech nemám žádnou aktuální originalPrice, ale našla jsem minimálně tyto produkty, které mají vyčíslenou slevu:
https://www.ikea.com/cz/cs/p/gerdie-polstar-bila-cerna-kocka-60410631/
https://www.ikea.com/cz/cs/p/ravaror-pohovka-vansta-tm-modra-70454441/
https://www.ikea.com/cz/cs/p/vigdis-povlak-na-polstar-bezovozelena-30506989/

**Comment by MartinaGelnerova** [comment]
opraveno

**Comment by MartinaGelnerova** [comment]
Data ze scrapu Ikea nejsou v pořádku:
- část items nemá vyplněné itemName (='')
- část items má chybnou cenu - viz vypsaný příklad zde: https://docs.google.com/spreadsheets/d/1ZE2cx5kB75VB0r7nnkcWYl4K6YD39Ex6etfwjiEV9Oc/edit?usp=sharing (2 zelené položky ceny sedí, zbytek je chybný)
- některé položky se mi tváří jako zlevněné, ale nejsou (to možná souvisí s cenami viz předchozí bod)

**Comment by rarous** [comment]
@MartinaGelnerova je to ještě aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous tohle už jsi opravil, zavírám issue
