### ISSUE TITLE
TSBohemia - weekly full scrape vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#836]
běžel 1 d 5 hrs (jak je možný, že to netime-outuje?)
sežral 235 cpus
Run log: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/dtM9AxDcrxA2Tf1br/runs/P8xLMNf8FBaLBV0Ik

**Comment by rarous** [comment]
@MartinaGelnerova je to stále aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous Ano, TSBohemia je aktuální. V tuto chvíli je full scrape vypnutý, ale správně by měl běžet 1x týdně kvůli aktualizaci metadat a doplnění produktů pro každodenní price-scrape.
