### ISSUE TITLE
Notino_cz/sk - low items count

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#848]
normálě CZ posílá 14k items, nyní 210, SK 12k => dnes 1 item za 6hrs scrape:face_palm:
Actor zřejmě nevidí produkty v kategoriích.

last run CZ:
https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/8jIanA0LXgjCGYFZd/runs/FJ3j3LOF5ra19rIiH#log

last run SK: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/tMWgZrDQ5baq0TxDY/runs/a40EWhA4Ord5cNz4V#log

**Comment by janfiedler** [comment]
Fixed
