### ISSUE TITLE
Mall_cz/sk - upravit BF scraper

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#858]
Mall změnil API a používá teď GraphQL, takže bude potřeba přepis actora.

**Comment by junkycoder** [comment]
BF cat: 
* https://www.mall.cz/kampan/black-friday
* https://www.mall.sk/kampan/black-friday

**Comment by junkycoder** [comment]
```sh
DEBUG We are on 125 page
DEBUG Got 80 items now 👈 tohle ..
DEBUG Has more pages.
DEBUG We are on 126 page
DEBUG Got 0 items now 👈 .. asi ukazuje, že nemáme všechny?
DEBUG That was last page
INFO  BasicCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
DEBUG BasicCrawler:SessionPool: Persisting state {"persistStateKeyValueStoreId":"mall-sessions","persistStateKey":"SDK_SESSION_POOL_STATE"}
DEBUG Statistics: Persisting state {"persistStateKey":"SDK_CRAWLER_STATISTICS_0"}
INFO  BasicCrawler: Final request statistics: {"requestsFinished":126,"requestsFailed":0,"retryHistogram":[126],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":1008,"requestsFinishedPerMinute":59,"requestsFailedPerMinute":0,"requestTotalDurationMillis":126961,"requestsTotal":126,"crawlerRuntimeMillis":127141}
Crawling finished.
DEBUG STATS saved!
INFO  {"pages":126,"items":9955,"itemsDuplicity":null}
```

**Comment by junkycoder** [comment]
BF CZ jede, ale sbírá jen několik prvních stránek  https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/FNg7ShQJHyiZ4mfDZ/runs/3wGr4iHHEgfsbnVx2#log

BF SK taky nedojde nakonec stránkování a končí na validaci https://console.apify.com/view/runs/l4YiHERymzJMP9Ml9 `missing columns: thirdPartySeller`

**Comment by MartinaGelnerova** [comment]
thirdPartySeller máme jako sloupec ve feedu, v BF není potřeba, můžu si to napárovat.
V tabulce v Keboole jsem ho odmazala, aby to na něm nepadalo.

**Comment by MartinaGelnerova** [comment]
koukala jsem na ta data Mall_cz:
jsou tam některé produkty, kde mám originalPrice > currentPrice, což nedává smysl. Když se na ty produkty kouknu, nemají originalPrice ani na webu uvedenou:
https://docs.google.com/spreadsheets/d/1gAi5lOF7l9FrByQMre3hfcVYdd5iEBxvsiUedOScvLE/edit#gid=2985557
Já si to můžu v datech odfiltrovat, jenom na to upozorňuju, že taháme něco, co v reálu není na webu vidět.

**Comment by junkycoder** [comment]
@MartinaGelnerova nemám tedy filtrovat (nesbírat) ty produkty originalPrice > currentPrice už v actoru rovnou?

**Comment by MartinaGelnerova** [comment]
@junkycoder Produkty určitě sbírat všechny! A nakonec u toho Mallu nech i ty "nesmyslné originalPrice". Ukázalo se totiž, že jsou to reálné originalPrice, které ale oni z důvodu zdražení produktu nezobrazují.
Vyřeším si to v datech v Keboole. Dík.

**Comment by MartinaGelnerova** [comment]
@junkycoder koukala jsem, že mall_sk upload do Kebooly taky padal na thirdPartySeller - sloupec jsem v Keboole odstranila a upload už proběhl. Nascheduluju.

**Comment by junkycoder** [comment]
@MartinaGelnerova u CZ padal upload na chybějících unitPrice fieldech. Doplnil jsem (nullama) a pustil oba BF runy znovu. 

Stránkování už dojde až nakonec, takže sbíráme up-to 10k produktů - to mi přijde strašně moc, ale namátková kontrola ukazuje, že to tak opravdu mají.

**Comment by rarous** [comment]
@MartinaGelnerova je to už ok? :)

**Comment by MartinaGelnerova** [comment]
@rarous ok, uzavírám,
