### ISSUE TITLE
Okay_cz/sk - opravit BF actora

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#859]
Bude potřeba přepis actora.
urls pro BF budou https://www.okay.cz/collections/black-friday-2022 a https://www.okay.sk/collections/black-friday-2022

**Comment by junkycoder** [comment]
https://services.mybcapps.com/bc-sf-filter/search/?shop=okay-elektro-cz.myshopify.com

**Comment by junkycoder** [comment]
EP pro BF = https://services.mybcapps.com/bc-sf-filter/search/?shop=okay-elektro-cz.myshopify.com&event_type=init&limit=70&tag=MKT%3ABlack%20Friday%5B22%5D%7B2432%7D

* Je jich tam víc, než ve výpisu kategorie BF - ten obsahuje jen "největší slevy".
* Max limit na stránku je 70

---
Update: 
https://services.mybcapps.com/bc-sf-filter/filter?shop=okay-elektro-cz.myshopify.com&page=1&limit=70&sort=title-ascending&display=grid&collection_scope=270817165354

**Comment by junkycoder** [comment]
@MartinaGelnerova už to sbírá. Pro `okay-cz-bf` i `okay-sk-bf` to na uvedených BF adresách najde 30 produktů. Prosím o kontrolu dat.

**Comment by MartinaGelnerova** [comment]
30 produktů je strašně málo - to je jenom takový top-výběr. Já potřebuju procrawlovat jednotlivé kategorie z této stránky https://www.okay.cz/pages/blackfriday a vzít vše, co má u sebe tag black-friday
![image](https://user-images.githubusercontent.com/82106162/200566237-f0b997a5-dd46-4f01-90fd-234977daff8f.png)

**Comment by junkycoder** [comment]
@MartinaGelnerova dobrá, tak teď procházíme celý shop a filtrujeme podle tagů (to je vlastně to co jsi zvýraznila).

**Comment by junkycoder** [comment]
Finally to sbírá všechno (FULL a BF, SK i CZ)! 

- [ ]  Apify SDK v3

**Comment by MartinaGelnerova** [comment]
ok

**Comment by MartinaGelnerova** [comment]
@junkycoder koukám, že některé běhy vrátí 0 items, nebo 3 items a jiné běhy jsou ok. Mohl bys na to ještě prosím kouknout?
Runy actora s přehledem items:
https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/2HPxuhQRIGPBCC9KZ#/runs

**Comment by junkycoder** [comment]
@MartinaGelnerova opraveno. Přejmeovali si tagy podle kterých filtrujeme BF produkty. Uvidíme, jak často to budou dělat.

**Comment by junkycoder** [comment]
Jen to teď sebralo asi o 2k více produktu na CZ i SK, tak prosím o kontrolu dat.

**Comment by rarous** [comment]
Předělal jsme to na SDK 3.x

**Comment by MartinaGelnerova** [comment]
@junkycoder Kuba přišel na to, že u Okay_cz/sk taháme do dat špatnou currentPrice. Zvládli byste to rychle opravit, ať ještě chytíme posledí data k BF a máme u nich správná čísla?
Příklad: https://www.okay.cz/products/cartridge-hp-c2p10ae-651-cerna?variant=39654970097706
Já v datech mám class="current_price" 599,-, ale správě tam má mít class="current_price_mz" 569,-
