### ISSUE TITLE
CZC_cz - BF actor vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#860]

**Comment by junkycoder** [comment]
@MartinaGelnerova opraveno, ale uploader má problém s chybějícím `paginationUrl` - je potřeba? Můžu dodat

Btw, @rarous, vycházel jsem z té nové alzy, ale nějak dlouho trvá, než se run ukončí i když to má prázdnou queue, nevíš proč?

**Comment by rarous** [comment]
Divný, mně to končí hned, když mám prázdnou queue

**Comment by MartinaGelnerova** [comment]
paginationUrl není potřeba, odstranila jsem sloupec v tabulce v Keboole a
už to běží. Díky
