### ISSUE TITLE
Rohlik_cz vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#861]
Last run: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/PEVAiXtTjfBAwaOa6/runs/gcfZ6bn0qyHRPEOum#log

**Comment by junkycoder** [comment]
Notes:

* Původni EP pro produkty z kategorie již nefunguje - https://www.rohlik.cz/services/frontend-service/products/300101019
* Původní EP pro seznam všech kategorii (vč. sub) stále funguje a lze využít - https://www.rohlik.cz/services/frontend-service/renderer/navigation/flat.json
* Nově EP pro získání všech ID produktů z kategorie je https://www.rohlik.cz/api/v1/categories/normal/300101019/products?page=0 - stránkování mají po max 100
* Počet produktů (kvůli stránkování) z kategorie získáme z EP https://www.rohlik.cz/api/v1/categories/normal/300120441/products/count
* Ceny a slevy získáme z EP https://www.rohlik.cz/api/v1/products/prices?products=1306143&products=1339269&products=1306137&products=1351545&products=1400683&products=1413728&products=1409972&products=1287235&products=1400692&products=1423873 kde jde vyžádat maximálně 10 produktů najednou

**Comment by salax** [comment]
fixed
