### ISSUE TITLE
Electroworld BF task - vrací currentPrice a originalPrice null

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#866]
run: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/jkVf98gi5AWhRXgcg/runs/XzYRuy2MvKoZXgzF7#log

**Comment by rarous** [comment]
@MartinaGelnerova nový actor proběhl tady: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/q2SdAbdXWKo4U1R5Y#/log
