### ISSUE TITLE
neuvěřitelné slevy v Auto Esa

### ISSUE THREAD

**Issue by P4sweR** [theodik/hlidac-shopu#871]
podívejte se prosím jaké uvádí slevy na autoesa.cz zda-li je normalní, že tam uvádí u ojetiny zlevněno z ceny nového vozu, ušetříte tak 380 tisíc!

**Comment by rarous** [comment]
@P4sweR děkujeme za podnět, ale to je spíše na podání k ČOI.

**Comment by P4sweR** [comment]
díky, ale vyjímalo by se to v té tabulce reálných procent udávaných slev

**Comment by rarous** [comment]
To bychom je museli dlouhodobě sledovat, aby se tam dostali, a to nemáme v plánu.

**Comment by P4sweR** [comment]
Aha! Takže sledujete jen některé eshopy a ty co se chovají jako šmejdi necháte plavat jo? Zklamání...

**Comment by rarous** [comment]
Sledujeme jen některé shopy, protože [provoz něco stojí a nemůžeme sledovat všechny](https://cc.cz/e-shopy-ukazuji-i-trojnasobne-vyssi-nez-realne-slevy-letosni-black-friday-je-posledni-bez-regulace/). Snažíme se sledovat shopy, které používá velké množství uživatelů a tak můžeme najít kompromis mezi snesitelnými náklady a užitečností pro naše uživatele.

**Comment by Florestev** [comment]
A co takhle trošku spravedlnosti vůči těm shopům co sledujete, přičemž jsou mnohem horší na scéně a ty co sami navrhujete na podání kontroly na ČOI by asi stálo za to sledovat ne?

**Comment by rarous** [comment]
Nebráníme se sponzoringu vývoje a provozu actorů pro takové shopy. :) Každopádně hledáme model, který nám umožní pokrýt náklady na provoz Hlídače shopů, abychom mohli opět začít přidávat nové actory. Je možné že během Q1 2023 se náš postoj změní.
