### ISSUE TITLE
Lidl_cz - scrape nevezme všechny produkty

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#980]
6.2. successful scrape vrátil jenom 2241 items
run: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/RS4d571fc6LANBU3X/runs/LgJIVEKRq1W76idgV#log

7.2. successful scrape vrátil 5926 items
run: https://console.apify.com/organization/iMWJjifpQdTwbkKYn/actors/tasks/RS4d571fc6LANBU3X/runs/8XNhHOlzY74jImmPj

Bežně vrací 7-8tis items.

V posledních scrapech chybí např:
https://www.lidl.cz/p/f2-paddleboard-sport-kajak-10-5/p100337236
https://www.lidl.cz/p/crivit-damske-funkcni-leginy/p100352878
https://www.lidl.cz/p/silvercrest-topinkovac-stb-950-a1/p100347708

Tenhle produkt nemám v datech vůbec:
https://www.lidl.cz/p/silvercrest-fitness-chytre-hodinky-s-barevnym-displejem/p100352227001

**Comment by rarous** [comment]
Aktuální scraping je dost neefektivní, přepíšu listing na API access.

**Comment by MartinaGelnerova** [comment]
už vyřešeno, zavírám
