### ISSUE TITLE
Kosik_cz dnes vrací 0 items

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#983]
ERROR HttpCrawler: Request failed and reached maximum retries. RequestError: Client network socket disconnected before secure TLS connection was established

run: https://console.apify.com/admin/users/iMWJjifpQdTwbkKYn/actors/tasks/wIx8FhzstQOLjBBKr/runs/382tqa4Etoy3VfiAI#log

**Comment by rarous** [comment]
Blokované proxy, stačilo změnit na vstupu.
