### ISSUE TITLE
Rozdílné grafy pro stejný výrobek

### ISSUE THREAD

**Issue by ivan-vanek** [theodik/hlidac-shopu#984]
Vypadá to že pro Panasonic RP-HT161E je více grafů pod různými jmény (dlouhý vs krátký) a ty jsou potom použity pro různé prodejce a tak u třeba Datartu je výrobek mnohem draží, ale přitom vypadá, že je naopak levný než je běžné. A u třeba Mironetu, který je mnohem levější zase, že je předražený.
https://sluchatka.heureka.cz/panasonic-rp-ht161e/#prehled/

* Datart cena 307,- graf https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.datart.cz%2FSluchatka-PANASONIC-RP-HT161E-K.html%3Futm_medium%3Dpriceindexer%26utm_source%3Dheureka.cz%26utm_term%3DPANRPHT161EK 
* Mironet cena 224,- graf https://www.hlidacshopu.cz/app/?url=https%3A%2F%2Fwww.mironet.cz%2Fpanasonic-rpht161ek-cerna-monitorovaci-stereo-sluchatka%2Bdp319625%2F

je možné že tohle se děje u více produktů

**Comment by rarous** [comment]
My ukazujeme vývoj ceny na daném e-shopu, neporovnáváme ceny mezi různými e-shopy.
