### ISSUE TITLE
Benu_cz - problém s neunikátním itemId

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#985]
tenhle shop je specifický, protože nemá unikátní itemId, ale všechno jedeme na kombinaci itemId + slug. Koukám, že ale ze scrapu mi poslední dobou leze pro dané itemId jenom jeden produkt - nedoplnili jste tam nějakou logiku, která to osekává na unique itemId?
Konkrétní příklad - tři produkty se stejným itemId 8592084417635, ale různým slugem:
https://www.benu.cz/sunar-premium-2-700g
https://www.benu.cz/sunar-premium-2-700g-baleni-3-ks
https://www.benu.cz/sunar-premium-2-700g-baleni-6-ks
A jakýkoliv další Sunar, co se nabízí ve třech variantách balení...
https://www.benu.cz/sunar-premium-3-700g
https://www.benu.cz/sunar-premium-4-700g

**Comment by salax** [comment]
fixed
