### ISSUE TITLE
Okay_cz - originalPrice mi chybí ve scrapovaných datech - doplnit pro BF

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#986]
Takže teď mají na webu vidět originalPrice, ale ve scrapnutých datech (okay-cz-browser) originalPrice nemám. A teď nevím, jestli je to tím, že se ty ceny objevily až během dne. Spustila jsem ručně scrape, ale poběží dlouho, tak uvidím až večer.
V každém případě extenze si originalPrice checkuje správně.
Akorát se nám extenze na webu pořád ještě nevykresluje...
Příklady slev:
https://www.okay.cz/products/sackovy-vysavac-severin-spowerz-zelos-bc-7049
https://www.okay.cz/products/roboticky-vysavac-concept-robocross-gyro-vr2110-2v1
https://www.okay.cz/products/roboticky-vysavac-cleanmate-rv600
https://www.okay.cz/products/roboticky-vysavac-irobot-roomba-j7

**Comment by rarous** [comment]
@MartinaGelnerova je to ještě aktuální?

**Comment by MartinaGelnerova** [comment]
@rarous Okay se v tuhle chvíli scrapuje jenom prodejní cena, originalPrice vůbec nescrapujeme (nebyl čas to neustále upravovat)
